# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"get_dataset": "utils00_core.ipynb",
         "rmse": "utils00_core.ipynb",
         "convert_strings_to_categories": "utils00_core.ipynb",
         "fill_missing_values_with_median": "utils00_core.ipynb",
         "make_polynomial_data": "utils00_core.ipynb",
         "PolynomialRegressor": "utils00_core.ipynb",
         "display_large": "utils00_core.ipynb",
         "rf_feature_importance": "utils00_core.ipynb",
         "plot_feature_importance": "utils00_core.ipynb",
         "plot_dendogram": "utils00_core.ipynb",
         "plot_fitting_graph": "utils00_core.ipynb",
         "plot_classifier_boundaries": "utils00_core.ipynb",
         "draw_tree": "utils01_structured.ipynb",
         "get_sample": "utils01_structured.ipynb",
         "add_datepart": "utils01_structured.ipynb",
         "is_date": "utils01_structured.ipynb",
         "train_cats": "utils01_structured.ipynb",
         "apply_cats": "utils01_structured.ipynb",
         "fix_missing": "utils01_structured.ipynb",
         "numericalize": "utils01_structured.ipynb",
         "scale_vars": "utils01_structured.ipynb",
         "proc_df": "utils01_structured.ipynb",
         "rf_feat_importance": "utils01_structured.ipynb",
         "ImageDownloader": "utils02_image_downloader.ipynb"}

modules = ["core.py",
           "structured.py",
           "image_downloader.py"]

doc_url = "https://lvwerra.github.io/dslectures/"

git_url = "https://github.com/lvwerra/dslectures/tree/master/"

def custom_doc_links(name): return None
